---
title: "classical_basal_cells_identification"
output: html_document
date: "2025-03-07"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library loading

```{r}
library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(glmGamPoi)
library(UCell)
```

```{r}
data <- Load10X_Spatial(data.dir = '../../../datashare/PDAC/visium_PDAC/Visium_FFPE_V43T08-041_D/outs/', filename = 'filtered_feature_bc_matrix.h5')
```

## Quality Control

```{r}
plot1 <- VlnPlot(data, features = "nCount_Spatial", assay = "Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(data, features = "nCount_Spatial", pt.size.factor = 3) + theme(legend.position = "right")
wrap_plots(plot1, plot2)
```

## Filtering

```{r, eval = TRUE}
treshold = Inf
outlier_spot <- rownames(data@meta.data[data@meta.data$nCount_Spatial>treshold,])

SpatialDimPlot(data, cells.highlight = outlier_spot, facet.highlight = TRUE, ncol = 3, pt.size.factor = 3)
filtered_data <- subset(data, nCount_Spatial < treshold & nCount_Spatial > 0)
```

```{r, eval = TRUE}
plot1 <- VlnPlot(filtered_data, features = "nCount_Spatial", assay = "Spatial", pt.size = 0.1) + NoLegend()
plot2 <- SpatialFeaturePlot(filtered_data, features = "nCount_Spatial", pt.size.factor = 3) + theme(legend.position = "right")
wrap_plots(plot1, plot2)
```


## Normalization

```{r}
options(future.globals.maxSize = 8000 * 1024^2)
normalized_data <- SCTransform(filtered_data, assay = "Spatial", verbose = FALSE)
```

## Gene expression visualization


```{r}
SpatialFeaturePlot(normalized_data, features = c("TFF1", "SPRR3"), pt.size.factor = 3)
```

## Uscores calculation based on cell markers 

```{r}
gene.sets <- list() 
gene.sets$classical <- c("TFF1","TFF2","TFF3","CEACAM6", "LGALS4", "ST6GALNAC1", "PLA2G10","TSPAN8","LYZ","MYO1A", "VSIG2", "CLRN3", "CDH17", "AGR3", "AGR2", "BTNL8", "ANXA10", "FAM3D", "CTSE", "REG4")
gene.sets$basal <- c("SERPINB3", "SPRR3","SERPINB4", "VGLL1","DHRS9", "SPRR1B", "KRT17", "KRT15", "TNS4", "SCEL", "KRT6A", "KRT7", "CST6", "LY6D", "FAM83A", "AREG", "FGFBP1", "GPR87", "LEMD1","S100A2","SLC2A1")
```

```{r}
obj <- AddModuleScore_UCell(normalized_data, features = gene.sets)
signature.names <- paste0(names(gene.sets), "_UCell")

#to fix the scale
map1 <- SpatialFeaturePlot(obj, features = signature.names[1], pt.size.factor = 3) +
  scale_fill_gradientn(limits = c(0, 1), colors = c('blue',  'yellow', 'red'))

map2 <- SpatialFeaturePlot(obj, features = signature.names[2], pt.size.factor = 3) +
  scale_fill_gradientn(limits = c(0, 1), colors = c('blue',  'yellow', 'red'))

wrap_plots(map1, map2)
```
